;;---------------------------------------------------------------------------------------------
;;-- [LWOTC] A BETTER ARSENAL (LITE)
;;-- This file defines a lot of behavior however this mod specifically focuses in on the 
;;-- on the elements the define the armor and item characteristics.
;;---------------------------------------------------------------------------------------------
;; Buffing rules used for full version:
;;
;; there is no consistent rule here for how buffs were applied.  
;; Look to the ";##   ;##" numbers to see the full version value was and the game default value
;;
;; Most all values had +1 to the default value.
;;---------------------------------------------------------------------------------------------
;; Note on Modding LongWar 2 for WOTC: LW is a significant overhaul to the game to do exactly 
;; as its name implies, make the game longer. My mods boost stats and scalars that greatly 
;; accelerate the speed to complete the game. To keep to the intent of LW2 there have been 
;; minimal changes that would progress the game too quickly but still give you the OP goodness
;; you want from this mod.
;;---------------------------------------------------------------------------------------------


[XComGame.X2Ability_ItemGrantedAbilitySet]
+CERAMIC_PLATING_HP_BONUS=1 ;2 ;0
+ALLOY_PLATING_HP_BONUS=2 ;3 ;0
+CHITEN_PLATING_HP_BONUS=3 ;4 ;0

NANOFIBER_VEST_HP_BONUS=3 ;4 ;2

HAZMAT_VEST_HP_BONUS=4 ;5 ;3

PLATED_VEST_HP_BONUS=4 ;5 ;3
PLATED_VEST_MITIGATION_CHANCE=100
PLATED_VEST_MITIGATION_AMOUNT=2 ;4 ;1

SCORCHCIRCUITS_HEALTH_BONUS=7 ;8 ;6
SCORCHCIRCUITS_APPLY_CHANCE=100

STASIS_VEST_HP_BONUS=6 ;7 ;5
STASIS_VEST_REGEN_AMOUNT=3 ;4 ;2
STASIS_VEST_MAX_REGEN_AMOUNT=9 ;11 ;8

PSIAMP_CV_STATBONUS=10 ;20 ;0
PSIAMP_MG_STATBONUS=20 ;30 ;10
PSIAMP_BM_STATBONUS=30 ;40 ;20

; Medium armor mitigation is set in LW_Overhaul.ini
MEDIUM_PLATED_HEALTH_BONUS=5 ;8 ;3
LIGHT_PLATED_HEALTH_BONUS=3 ;5 ;1
LIGHT_PLATED_MOBILITY_BONUS=5 ;7 ;1
LIGHT_PLATED_DODGE_BONUS=10 ;25 ;5
HEAVY_PLATED_HEALTH_BONUS=6 ;9 ;2
HEAVY_PLATED_MITIGATION_CHANCE=100 ;100 ;0
HEAVY_PLATED_MITIGATION_AMOUNT=4 ;6 ;0
LIGHT_POWERED_HEALTH_BONUS=6 ;9 ;3
LIGHT_POWERED_MOBILITY_BONUS=6 ;10 ;2
LIGHT_POWERED_DODGE_BONUS=25 ;35 ;15
MEDIUM_POWERED_HEALTH_BONUS=10 ;12 ;8
MEDIUM_POWERED_MITIGATION_AMOUNT=5 ;7 ;2
MEDIUM_POWERED_MITIGATION_CHANCE=100
HEAVY_POWERED_HEALTH_BONUS=8 ;10 ;5
HEAVY_POWERED_MITIGATION_AMOUNT=6 ;8 ;1
HEAVY_POWERED_MITIGATION_CHANCE=100
APROUNDS_PIERCE=3 ;4 ;2
TALON_CRITCHANCE=50 ;100 ;10
TALON_CRIT=2 ;3 ;1


[DLC_3.X2Ability_DLC_Day90ItemGrantedAbilitySet]
SPARK_PLATED_HEALTH_BONUS=5 ;8 ;3
SPARK_PLATED_MOBILITY_BONUS=4 ;6 ;1
SPARK_PLATED_MITIGATION_AMOUNT=3 ;5 ;1
SPARK_PLATED_MITIGATION_CHANCE=100

SPARK_POWERED_HEALTH_BONUS=10 ;12 ;8
SPARK_POWERED_MOBILITY_BONUS=5 ;8 ;2
SPARK_POWERED_MITIGATION_AMOUNT=4 ;6 ;2
SPARK_POWERED_MITIGATION_CHANCE=100

[XComGame.X2Item_DefaultAmmo]
BLUESCREEN_DMGMOD=4 ;5 ;3
BLUESCREEN_HACK_DEFENSE_CHANGE=0


[DLC_2.X2Ability_DLC_Day60ItemGrantedAbilitySet]
MEDIUM_ALIEN_HEALTH_BONUS=5
MEDIUM_ALIEN_MOBILITY_BONUS=1
MEDIUM_ALIEN_MITIGATION_AMOUNT=1
MEDIUM_ALIEN_MITIGATION_CHANCE=100

HEAVY_ALIEN_HEALTH_BONUS=6
HEAVY_ALIEN_MOBILITY_BONUS=0
HEAVY_ALIEN_MITIGATION_AMOUNT=1
HEAVY_ALIEN_MITIGATION_CHANCE=100

HEAVY_ALIEN_MK2_HEALTH_BONUS=7
HEAVY_ALIEN_MK2_MOBILITY_BONUS=0
HEAVY_ALIEN_MK2_MITIGATION_AMOUNT=2
HEAVY_ALIEN_MK2_MITIGATION_CHANCE=100

LIGHT_ALIEN_HEALTH_BONUS=4
LIGHT_ALIEN_MOBILITY_BONUS=1
LIGHT_ALIEN_DODGE_BONUS=15

LIGHT_ALIEN_MK2_HEALTH_BONUS=5
LIGHT_ALIEN_MK2_MOBILITY_BONUS=2
LIGHT_ALIEN_MK2_DODGE_BONUS=20

HEAVY_ALIEN_PANIC_CHANCE=10
MEDIUM_ALIEN_PANIC_CHANCE=10
LIGHT_ALIEN_PANIC_CHANCE=10

HEAVY_ALIEN_PANIC_PER_POD=1
MEDIUM_ALIEN_PANIC_PER_POD=1
LIGHT_ALIEN_PANIC_PER_POD=1

ICARUS_JUMP_CHARGES=3 ;5 ;2
SHADOWFALL_CHARGES=2 ;3 ;1

FREEZINGLASH_MAX_RANGE=1152; 12 tiles in units
FREEZINGLASH_MIN_RULER_FREEZE_DURATION=2
FREEZINGLASH_MAX_RULER_FREEZE_DURATION=2



[XComGame.X2Effect_BiggestBooms]
CRIT_CHANCE_BONUS=75 ;100 ;50
CRIT_DAMAGE_BONUS=4 ;5 ;3

[XComGame.X2Effect_TracerRounds]
AimMod=10 ;20 ;5


[LWUtilities.Helpers_LW]

; Limit heavy weapons to specific classes
ClassLimitHeavyWeapons=true ;false ;true


[XComGame.X2Effect_CombatStims]
ARMOR_MITIGATION=3 ;5 ;2