;;---------------------------------------------------------------------------------------------
;; [LWOTC] A Better Rookie (LITE)
;;---------------------------------------------------------------------------------------------
;;---------------------------------------------------------------------------------------------
;;-- DIY Modding:
;;-- On each line that has been changed is a value after the ";" to the far right.  
;;-- This is the original value the game defined after a XCOM2 devs spent a zillion hours of 
;;-- game testing and balancing. If you do not like the value I gave you can choose a new one 
;;-- knowing both what XCOM2/WOTC intended and what I gave it.
;;
;;-- CharacterBaseStats[eStat_EXAMPLE]=10	;(# non-LITE value) # game original value
;;-- CharacterBaseStats[eStat_EXAMPLE]=10	;(25) 5
;;----------------------------------------------------------------------------------------------


[XComGame.X2StrategyGameRulesetDataStructures]
; Soldier Progression
AbilityPointCosts[0]=0 ; Squaddie
AbilityPointCosts[1]=10 ;5 ;10 ; LCpl
AbilityPointCosts[2]=10 ;5 ;10 ; Cpl
AbilityPointCosts[3]=10 ;5 ;10 ; Sgt
AbilityPointCosts[4]=15 ;10 ;20 ; SSgt
AbilityPointCosts[5]=15 ;10 ;20 ; TSgt
AbilityPointCosts[6]=15 ;10 ;20 ; GSgt
AbilityPointCosts[7]=35 ;20 ;40 ; MSgt

; Used for XCOM abilities gained by the Faction heroes which are really powerful
PowerfulAbilityPointCost=20 ;10 ;25

; Lightly Wounded, Wounded, Gravely Wounded
WoundStates[0]=(WoundStateHealthPercents[0]=80, WoundStateHealthPercents[1]=30)	 ;Easy
WoundStates[1]=(WoundStateHealthPercents[0]=80, WoundStateHealthPercents[1]=30)	 ;Normal
WoundStates[2]=(WoundStateHealthPercents[0]=80, WoundStateHealthPercents[1]=30)	 ;Classic
WoundStates[3]=(WoundStateHealthPercents[0]=80, WoundStateHealthPercents[1]=30)	 ;Impossible

; Will recovery configuration
WillRecoveryDays[eMentalState_Shaken]=(MinDays=8, MaxDays=14)
WillRecoveryDays[eMentalState_Tired]=(MinDays=4, MaxDays=8)
WillRecoveryDays[eMentalState_Ready]=(MinDays=0, MaxDays=2)
;F: WillRecoveryDays[eMentalState_Shaken]=(MinDays=1, MaxDays=1)
;F: WillRecoveryDays[eMentalState_Tired]=(MinDays=1, MaxDays=1)
;F: WillRecoveryDays[eMentalState_Ready]=(MinDays=0, MaxDays=1)
;O: WillRecoveryDays[eMentalState_Shaken]=(MinDays=10, MaxDays=16)
;O: WillRecoveryDays[eMentalState_Tired]=(MinDays=6, MaxDays=10)
;O: WillRecoveryDays[eMentalState_Ready]=(MinDays=0, MaxDays=4)



;[XComGame.X2StrategyGameRulesetDataStructures]

;-AbilityPointCosts[0]=0 ; Squaddie
;-AbilityPointCosts[1]=10 ; Corporal
;-AbilityPointCosts[2]=11 ; Sergeant
;-AbilityPointCosts[3]=12 ; Lieutenant
;-AbilityPointCosts[4]=13 ; Captain
;-AbilityPointCosts[5]=14 ; Major
;-AbilityPointCosts[6]=15 ; Colonel

;+AbilityPointCosts[0]=0 ; Squaddie
;+AbilityPointCosts[1]=30 ; Corporal
;+AbilityPointCosts[2]=31 ; Sergeant
;+AbilityPointCosts[3]=32 ; Lieutenant
;+AbilityPointCosts[4]=33 ; Captain
;+AbilityPointCosts[5]=34 ; Major
;+AbilityPointCosts[6]=35 ; Colonel
;+AbilityPointCosts[7]=36; Brigadier

