;;---------------------------------------------------------------------------------------------
;; [LWOTC] A Better Rookie (LITE)
;;---------------------------------------------------------------------------------------------
;;---------------------------------------------------------------------------------------------
;;-- DIY Modding:
;;-- On each line that has been changed is a value after the ";" to the far right.  
;;-- This is the original value the game defined after a XCOM2 devs spent a zillion hours of 
;;-- game testing and balancing. If you do not like the value I gave you can choose a new one 
;;-- knowing both what XCOM2/WOTC intended and what I gave it.
;;
;;-- BLADEMASTER_DMG=10	;# non-LITE value ;# game original value
;;-- BLADEMASTER_DMG=2 ;3 ;1
;;-- 
;;-- LW left out changing the standard abilities in WOTC. Not certain if they were assuming
;;-- the default values would come through or if they wanted them removed from the class.
;;----------------------------------------------------------------------------------------------

[XComGame.X2Ability_RangerAbilitySet]
BLADEMASTER_DMG=2 ;4 ;1
INSTINCT_DMG=2 ;3 ;2
INSTINCT_CRIT=20 ;30 ;0
SHADOWSTRIKE_AIM=60 ;100 ;50
SHADOWSTRIKE_CRIT=55 ;70 ;50
REAPER_COOLDOWN=3 ;2 ;4
;;---Added for A.B.R.LWOTC
BLADEMASTER_AIM=20 ;40 ;noval
STEALTH_CHARGES=2 ;3 ;noval
MAX_UNTOUCHABLE=1 ;3 ;noval
RAPIDFIRE_AIM=-10 ;0 ;noval -15
RUNANDGUN_COOLDOWN=2 ;0 ;noval 4


[XComGame.X2Ability_GrenadierAbilitySet]
VOLATILE_DAMAGE=1 ;2 ;0
VOLATILE_RADIUS=1.5 ;2.0f ;1.0f
DEMO_HIT_BONUS=55 ;75 ;50
DEMOLITION_COOLDOWN=3 ;2 ;5
CHAINSHOT_HIT_MOD=-5 ;0 ;-10
SATURATION_FIRE_COOLDOWN=5 ;2 ;7
SATURATION_TILE_WIDTH=6 ;8 ;5
SATURATION_DESTRUCTION_CHANCE=60 ;70 ;50
BLAST_PADDING_DMG_ADJUST=0.50f
;;---Added for A.B.R.LWOTC
BULLET_SHRED=3 ;4 ;noval 3
HOLOTARGET_BONUS=20 ;25 ;noval 15
ORDNANCE_BONUS=2 ;3 ;noval 1
HAILOFBULLETS_COOLDOWN=4 ;2 ;noval 6
BULLETSHRED_COOLDOWN=3 ;1 ;noval 4

[XComGame.X2Ability_SharpshooterAbilitySet]
DEADEYE_COOLDOWN=2 ;1 ;3
DEADEYE_AIM_MULTIPLIER=0.20f ;0.30 ;0.15f
SERIAL_COOLDOWN=5 ;2 ;7
;;---Added for A.B.R.LWOTC
HITWHEREITHURTS_CRIT=20 ;30 ;10
STEADYHANDS_AIM_BONUS=15 ;50 ;10
STEADYHANDS_CRIT_BONUS=15 ;20 ;10
FACEOFF_COOLDOWN=3 ;1 ;4
FANFIRE_COOLDOWN=3 ;1 ;4
KILLZONE_COOLDOWN=3 ;1 ;4
SHARPSHOOTERAIM_BONUS=30 ;60 ;20
LIGHTNINGHANDS_COOLDOWN=2 ;0 ;4


[XComGame.X2Ability_SpecialistAbilitySet]
REVIVAL_PROTOCOL_CHARGES=2 ;3 ;2
;;---Added for A.B.R.LWOTC
UNDER_PRESSURE_BONUS=15 ;20 ;10
MIST_RADIUS=8 ;12 ;5
MIST_RANGE=12 ;20 ;10
GREMLIN_PERK_EFFECT_WINDOW=1.75
GREMLIN_ARRIVAL_TIMEOUT=20
FIELD_MEDIC_BONUS=3 ;4 ;2
GUARDIAN_PROC=50
COMBAT_PROTOCOL_CHARGES=3 ;4 ;2
REVIVAL_PROTOCOL_CHARGES=2 ;3 ;1
RESTORATIVE_MIST_CHARGES=2 ;3 ;1
CAPACITOR_DISCHARGE_CHARGES=2 ;3 ;1
SCANNING_PROTOCOL_CHARGES=2 ;8 ;1
HAYWIRE_PROTOCOL_COOLDOWN=3 ;1 ;4

[XComGame.X2Ability_PsiOperativeAbilitySet]
SOULFIRE_COOLDOWN=2 ;1 ;2
STASIS_COOLDOWN=2 ;0 ;4
INSANITY_COOLDOWN=1 ;0 ;1
DOMINATION_COOLDOWN=4 ;2 ;7
NULL_LANCE_COOLDOWN_PLAYER=3 ;1 ;4
VOID_RIFT_COOLDOWN=3 ;2 ;5
SOULSTEAL_MULTIPLIER=0.5f
SCHISM_DMG=(Damage=3, Spread=1, Rupture=2, DamageType="Psi")
;;---Added for A.B.R.LWOTC
INSPIRE_COOLDOWN=2 ;1 ;4
SOLACE_DISTANCE_SQ=16 ;32 ;16		; 4 tiles squared
NULL_LANCE_COOLDOWN_AI=2
NULL_LANCE_GLOBAL_COOLDOWN_AI=0
VOID_RIFT_RADIUS=6 ;8 ;5
VOID_RIFT_RANGE=28 ;35 ;25
VOID_RIFT_INSANITY_CHANCE=50
VOID_RIFT_INSANITY_FX_VISUALIZATION_DELAY=1.0f
PSI_OP_MIND_CONTROL_COOLDOWN_PLAYER=4 ;2 ;5
PSI_OP_MIND_CONTROL_LASTS_NUMBER_TURNS=3

[XComGame.X2Ability_HackRewards]
ReduceDetection_DetectionModifierBonus=0.20 ;0.30 ;0.15
IncreaseDetection_DetectionModifierBonus=-0.20 ;-0.30 ;-0.15
AlloyPadding_ApplicationChance=53 ;75 ;33
SKULLOuch_DAMAGE=(Damage=4, Spread = 0, PlusOne = 36, Crit = 0, Pierce = 999, Shred=0, Tag = "")
;F: SKULLOuch_DAMAGE=(Damage=6, Spread = 0, PlusOne = 46, Crit = 0, Pierce = 999, Shred=0, Tag = "")
;O: SKULLOuch_DAMAGE=(Damage=3, Spread = 0, PlusOne = 26, Crit = 0, Pierce = 999, Shred=0, Tag = "")
Jammed_DefenseBonus=20 ;30 ;10
TargetingAimAndCrit_AimBonus=30 ;50 ;20
TargetingAimAndCrit_CritBonus=30 ;50 ;20
TargetingDodge_DodgeBonus=35 ;55 ;25
TargetingCrit_CritBonus=35 ;55 ;25

[DLC_3.X2Ability_SparkAbilitySet]
SACRIFICE_COOLDOWN=4 ;2 ;6
SACRIFICE_DISTANCE_SQ=16 ;32 ;16	; 4 tiles squared
SACRIFICE_RADIUS_METERS=8.0 ;10.0 ;6.0	; 4 tiles
SACRIFICE_DEFENSE=20 ;30 ;10
SACRIFICE_ARMOR=2 ;4 ;1
NOVA_ENV_DMG=15 ;25 ;10
OVERDRIVE_COOLDOWN=3 ;1 ;5
BULWARK_ARMOR=2 ;3 ;1
STRIKE_COOLDOWN=2 ;1 ;4
STRIKE_HITMOD=30 ;40 ;20
REPAIR_CHARGES=2 ;4 ;2
REPAIR_HP=8 ;8 ;6
SPARK_DEATH_EXPLOSION_RADIUS_METERS=5.0 ;8.5 ;4.5
SPARK_PSI_EXPLOSION_ENV_DMG=30 ;50 ;20
NOVA_COOLDOWN=1 ;0
NOVA_RADIUS_METERS=5 ;6 ;4
HUNTERPROTOCOL_CHANCE=53 ;66 ;33
BOMBARD_CHARGES=2 ;3 ;1
BOMBARD_NUM_COOLDOWN_TURNS=0
BOMBARD_DAMAGE_RADIUS_METERS=4 ;6 ;4	-3 tiles in meters (1 tile = 1.5 meters)
BOMBARD_ENV_DMG=30 ;50 ;20
WAIT_SECS_PER_TILE=0.1
RAINMAKER_DMG_ROCKETLAUNCHER=3 ;4 ;2
RAINMAKER_DMG_SHREDDERGUN=3 ;4 ;2
RAINMAKER_DMG_SHREDSTORM=3 ;4 ;2
RAINMAKER_DMG_FLAMETHROWER=3 ;4 ;2
RAINMAKER_DMG_FLAMETHROWER2=3 ;4 ;2
RAINMAKER_DMG_BLASTERLAUNCHER=3 ;4 ;2
RAINMAKER_DMG_PLASMABLASTER=3 ;4 ;2

;[XComGame.X2Effect_Fortress]
;+DamageImmunities="BlazingPinions"

[XComGame.X2Effect_Shredder]
ConventionalShred=2 ;3 ;1
MagneticShred=3 ;4 ;2
BeamShred=4 ;5 ;3

[XComGame.X2Effect_Reaper]
DMG_REDUCTION=3 ;4 ;3

[XComGame.X2Effect_HoloTarget]
HitMod=15 ;25 ;10

[XComGame.X2Ability_TemplarAbilitySet]
; Remove the semicolons behind the two lines below and add a value to the "+" line if you want to customize Pillar's cooldown.
-PILLAR_COOLDOWN=1
+PILLAR_COOLDOWN=1 ;0 ;1

; Customize the base hit chance in the "+" line all you want.
-StunStrikeHitChance=65
+StunStrikeHitChance=80 ;95 ;75

; Remove the semicolons behind the two lines below and add a value to the "+" line if you want to customize the Focus aim modifier value.
-StunStrikeFocusMultiplierHitChance=5
+StunStrikeFocusMultiplierHitChance=5 ;6 ;5

; Customize the cooldown in the "+" line all you want.
-STUNSTRIKE_COOLDOWN=3
+STUNSTRIKE_COOLDOWN=1 ;0 ;2

;;-------------------------------------------------------------
;;Added from A.B.Recruit WOTC
[XComGame.X2Ability_HeavyWeapons]
SHREDDER_GUN_TILE_LENGTH=20 ;25 ;15
SHREDDER_GUN_TILE_WIDTH=7 ;10 ;5
SHREDSTORM_TILE_LENGTH=20 ;35 ;25
SHREDSTORM_TILE_WIDTH=8 ;11 ;6
FLAMETHROWER_TILE_LENGTH=17 ;25 ;15
FLAMETHROWER_TILE_WIDTH=7 ;10 ;5

[XComGame.X2Condition_Bondmate]
BondRangeTiles[0]=0 ;0 ;0 range when no bond
BondRangeTiles[1]=6 ;8 ;6 ; range at bond level 1
BondRangeTiles[2]=7 ;9 ;7 ; range at bond level 2
BondRangeTiles[3]=8 ;10 ;8 ; range at bond level 3

[XComGame.X2Ability_Civilian]
EasyToHitMod=10 ;0 ;20

[XComGame.X2Ability_MimicBeacon]
MIMIC_BEACON_TURNS_LENGTH=2 ;3 ;1
GuaranteedToHitMod=1000 ;50 ;1000

[XComGame.X2Ability_ReaperAbilitySet]
InfiltrationHackBonus=35 ;75 ;25
ShadowMobilityMod=1.5 ;2.0 ;1.375 ;multiplier of 1.5 will increase mobility by 50%
ShadowCooldown=1 ;0 ;1
ShadowCharges=2 ;3 ;1
ShadowRisingCharges=2 ;3 ;1
ClaymoreCharges=2 ;3 ;1
ClaymoreRange=20 ;25 ;15
HighlandsCharges=2 ;3 ;1
HomingMineRadius=3.0f ;4.5f ;2.5f
HomingShrapnelBonusRadius=2.2f ;3.0f ;1.8f
HomingMineEnvironmentDamage=20 ;30 ;10
HomingMineDamage=(Damage=6, Spread = 0, PlusOne = 0, Crit = 0, Pierce = 0, Shred=2, Tag = "", DamageType="Explosion")
HomingShrapnelDamage=(Damage=9, Spread = 0, PlusOne = 0, Crit = 0, Pierce = 0, Shred=3, Tag = "", DamageType="Explosion")
;F: HomingMineDamage=(Damage=8, Spread = 0, PlusOne = 0, Crit = 0, Pierce = 0, Shred=2, Tag = "", DamageType="Explosion")
;F: HomingShrapnelDamage=(Damage=11, Spread = 0, PlusOne = 0, Crit = 0, Pierce = 0, Shred=3, Tag = "", DamageType="Explosion")
;O: HomingMineDamage=(Damage=5, Spread = 0, PlusOne = 0, Crit = 0, Pierce = 0, Shred=2, Tag = "", DamageType="Explosion")
;O: HomingShrapnelDamage=(Damage=8, Spread = 0, PlusOne = 0, Crit = 0, Pierce = 0, Shred=3, Tag = "", DamageType="Explosion")
; shrapnel environment damage applies on top of the base mine environment damage
HomingShrapnelEnvironmentDamage=20 ;30 ;10
RemoteStartDamageMultiplier=2.0f ;3.0f ;2.0f
RemoteStartRadiusMultiplier=2.0f ;3.0f ;2.0f
StingCooldown=3 ;1 ;4
StingCharges=2 ;3 ;1
BloodTrailDamage=1 ;3 ;1
NeedlePierce=2 ;4 ;2
RemoteStartCooldown=1 ;0 ;2
PaleHorseCritBoost=10 ;25 ;5
PaleHorseMax=25 ;30 ;20
BanishFirstShotAimMod=-15
BanishSubsequentShotsAimMod=-15

[XComGame.X2Ability_TemplarAbilitySet]
FOCUS1MOBILITY=2 ;5 ;1
FOCUS1DODGE=15 ;20 ;10
FOCUS1RENDDAMAGE=2 ;3 ;1
FOCUS2MOBILITY=3 ;6 ;2
FOCUS2DODGE=25 ;30 ;20
FOCUS2RENDDAMAGE=3 ;4 ;2
FOCUS3MOBILITY=4 ;7 ;3
FOCUS3DODGE=30 ;35 ;25
FOCUS3RENDDAMAGE=4 ;5 ;3
REND_STUN_AND_KNOCKBACK_CHANCE=0.10f ;0.20f ;0.05f
REND_DISORIENT_CHANCE=0.3f ;0.8f ;0.1f
OVERCHARGE_FOCUS_CHANCE=43 ;66 ;33
AmplifyBonusDamageMult=0.50f ;1.20f ;0.33f
AmplifyMinBonusDamage=3 ;3 ;2
AMPLIFY_COOLDOWN=1 ;0 ;1
VoltHitMod=18 ;20 ;15
ChannelChance=30 ;50 ;20
ChannelPsionicChance=60 ;70 ;50
ChannelDropItemTemplate="BasicFocusLoot"
ReflectShotHitChance=80 ;85 ;75
INVERT_COOLDOWN=1 ;0 ;2
EXCHANGE_COOLDOWN=1 ;0 ;2
FocusDamageBoostAbilities="Rend"
FocusDamageBoostAbilities="ArcWave"
FocusDamageBoostAbilities="TemplarBladestormAttack"
GhostRendFocusCost=1
GhostFocusCost=1 ;1 ;2
GhostHPPerFocus=4
GHOST_CHARGES=2 ;3 ;1
GhostOnlyAbilities="GhostKill"
GhostOnlyAbilities="GhostInit"
IONICSTORM_RADIUS_METERS=2.5 ;3.5 ;1.5
IonicStormTargetMinDelay=0.18
IonicStormTargetMaxDelay=0.32
IONICSTORM_COOLDOWN=4 ;2 ;5
FocusKillAbilities="Rend"
FocusKillAbilities="ArcWave"
FocusKillAbilities="IonicStorm"
VoidConduitInitialDamage=3 ;4 ;3
VoidConduitPerActionDamage=2 ;3 ;2
VoidConduitHPMod=1.0f
VOIDCONDUIT_COOLDOWN=1 ;0 ;1
StunStrikeDisorientNumTurns=2 ;3 ;2
StunStrikeDisorientFocusMultiplier=25 ;30 ;20
ArcWaveConeEndDiameterTiles=6 ;8 ;5
ArcWaveConeLengthTiles=8 ;10 ;6
MEDITATION_PREPARATION_STARTING_FOCUS=2 ;3 ;1

[XComGame.XComGameState_Effect_TemplarFocus]
StartingFocus=2 ;2 ;0
StartingMaxFocus=4 ;6 ;2
IncreaseFocusAbilities="DeepFocus"
IncreaseFocusAbilities="WarlockLevelM3"
IncreaseFocusAbilities="WarlockFocusM4"
IncreaseFocusAbilities="WarlockLevelM4"

[XComGame.X2Ability_SkirmisherAbilitySet]
FullThrottleMobility=3 ;6 ;2
INTERRUPT_CHARGES=2 ;3 ;1
NUM_PARKOUR_ACTION_POINTS=1 ;1 ;1
RECKONING_DMG=3 ;4 ;2
RECKONING_AIM=20 ;30 ;10
WHIPLASH_BASEDAMAGE=(Damage=6, Spread=0, PlusOne=0, Crit=0, Pierce=0, Shred=0, Tag="", DamageType="Electrical" ;WHIPLASH_CHARGES=2 ;3 ;1
JUDGMENT_APPLYCHANCEATTACKVAL=50
JUDGMENT_MINCHANCE=5 ;10 ;5
JUDGMENT_MAXCHANCE=50 ;55 ;45
JUSTICE_HIT_BONUS=30 ;45 ;25
JUSTICE_COOLDOWN=4 ;1 ;5  -- added this variable but it has no effect
WRATH_HIT_BONUS=30 ;45 ;25
RECKONING_COOLDOWN=4 ;2 ;6
BATTLELORD_ACTIONS=3 ;3 ;2

[XComGame.X2Effect_ZeroIn]
CritPerShot=15 ;20 ;10
LockedInAimPerShot=15 ;20 ;10

[XComGame.X2Ability_OfficerTrainingSchool]
LIGHTNING_STRIKE_MOVE_BONUS=4 ;6 ;3
LIGHTNING_STRIKE_NUM_TURNS=4 ;5 ;3
VENGEANCE_DURATION=3 ;4 ;2
VENGEANCE_MIN_RANK=0
;----------------------------------------------------------

[DLC_3.X2Effect_DLC_3Overdrive]
ShotModifier=0 ;10) -15

[DLC_3.X2Ability_LostTowersShenAbilitySet]
SHENCOMBATPROTOCOL_COOLDOWN=1 ;0) 3
SHENCAPACITORDISCHARGE_COOLDOWN=1 ;0) 5
SHENGREMLINHEAL_CHARGES=4 ;4) 4