;;---------------------------------------------------------------------------------------------
;; [LWOTC] A Better Rookie (LITE)
;;---------------------------------------------------------------------------------------------
;;---------------------------------------------------------------------------------------------
;;-- DIY Modding:
;;-- On each line that has been changed is a value after the ";" to the far right.  
;;-- This is the original value the game defined after a XCOM2 devs spent a zillion hours of 
;;-- game testing and balancing. If you do not like the value I gave you can choose a new one 
;;-- knowing both what XCOM2/WOTC intended and what I gave it.
;;
;;-- CharacterBaseStats[eStat_EXAMPLE]=10	;(# non-LITE value) # game original value
;;-- CharacterBaseStats[eStat_EXAMPLE]=10	;(25) 5
;;----------------------------------------------------------------------------------------------

[XComGame.X2StatusEffects]
BLEEDINGOUT_TURNS=5 ;6 ;4
BLEEDOUT_BONUS_ROLL=50			; GTS Bonus
BLEEDOUT_ROLL=100				; This is the size of the die

; This is overridden if USE_ALT_BLEEDOUT_RULES=true. ALT rules are set in LW_Overhaul.ini and don't use will
BLEEDOUT_BASE=20				; Will - this value is Bleedoutchance

DISORIENTED_TURNS=2 ;1 ;2
DISORIENTED_MOBILITY_ADJUST=-6 ;-2 ;-6
DISORIENTED_AIM_ADJUST=-20 ;-5 ;-20
DISORIENTED_WILL_ADJUST=-20 ;-5 ;-20

POISONED_TURNS=4 ;1 ;4
POISONED_MOBILITY_ADJUST=-4 ;-1 ;-4
POISONED_AIM_ADJUST=-20 ;-5 ;-20
POISONED_INITIAL_SHED=0
POISONED_PER_TURN_SHED=40 ;100 ;30
POISONED_DAMAGE=1
POISONED_INFECT_DISTANCE=0
POISONED_INFECT_PERCENTAGE=0

MAX_PANICKING_UNITS=2 ;0 ;2
PANIC_WILL_ADJUST=0
PANIC_SUCCESS_WILL_MOD=0

BURNING_TURNS=2 ;1 ;2
ACID_BURNING_TURNS=1

; Do panic check and then decrement Will by these amounts
PANIC_STRENGTH_TAKE_DAMAGE=0
PANIC_STRENGTH_LOS_FRIENDLY_DEATH=0			; At MYRANK -PANIC_LOWER_RANK or higher, unless...
PANIC_STRENGTH_LOS_HIGHER_FRIENDLY_DEATH=5		; At MYRANK +PANIC_HIGHER_RANK
PANIC_STRENGTH_ALLY_PANICS=0
PANIC_HIGHER_RANK=3
PANIC_LOWER_RANK=1

[XComGame.X2TacticalGameRuleset]
UnitHeightAdvantage=2 ;2 ;3						; Number of tiles a unit must be >= another unit to be given height advantage for shooting
UnitHeightAdvantageBonus=15 ;20 ;10					; Amount of additional Aim granted to a unit with height advantage
XComIndestructibleCoverMaxDifficulty=0		; The highest difficulty at which to give xcom the advantage of indestructible cover (from missed shots)

[XComGame.X2AbilityToHitCalc_StandardAim]
LOW_COVER_BONUS=30
HIGH_COVER_BONUS=45

SQUADSIGHT_CRIT_MOD=3 ;5 ;0
SQUADSIGHT_DISTANCE_MOD=8 ;12 ;0

; Rookies
BaseXComHitChanceModifier[0]=1.0 ;2.0 ;0.0
MissStreakChanceAdjustment[0]=0
HitStreakChanceAdjustment[0]=0
SoldiersLostXComHitChanceAdjustment[0]=0
SoldiersLostAlienHitChanceAdjustment[0]=100
AlienVsTheLostHitChanceAdjustment[0]=0
TheLostVsAlienHitChanceAdjustment[0]=0

; Veteran
BaseXComHitChanceModifier[1]=1.0 ;2.0 ;0.0
MissStreakChanceAdjustment[1]=0
HitStreakChanceAdjustment[1]=0
SoldiersLostXComHitChanceAdjustment[1]=0
SoldiersLostAlienHitChanceAdjustment[1]=100
AlienVsTheLostHitChanceAdjustment[1]=10
TheLostVsAlienHitChanceAdjustment[1]=0

; Commander
BaseXComHitChanceModifier[2]=1.0 ;2.0 ;0.0
MissStreakChanceAdjustment[2]=0
HitStreakChanceAdjustment[2]=0
SoldiersLostXComHitChanceAdjustment[2]=0
SoldiersLostAlienHitChanceAdjustment[2]=100
AlienVsTheLostHitChanceAdjustment[2]=20
TheLostVsAlienHitChanceAdjustment[2]=0

; Legend
BaseXComHitChanceModifier[3]=1.0 ;2.0 ;0.0
MissStreakChanceAdjustment[3]=0
HitStreakChanceAdjustment[3]=0
SoldiersLostXComHitChanceAdjustment[3]=0
SoldiersLostAlienHitChanceAdjustment[3]=100
AlienVsTheLostHitChanceAdjustment[3]=20
TheLostVsAlienHitChanceAdjustment[3]=0

[XComGame.X2Effect_Suppression]
SoldierTargetAimPenalty=-25 ;-5 ;-25 		;	penalty suffered when suppressed by an xcom unit
AlienTargetAimPenalty=-25 ;-55 ;-25			;	penalty suffered when suppressed by an alien unit

[XComGame.X2Effect_BiggestBooms]
CRIT_CHANCE_BONUS=60 ;80 ;50
CRIT_DAMAGE_BONUS=4 ;5 ;3

[XComGame.X2Effect_TracerRounds]
AimMod=10 ;20 ;5

[XComGame.X2HackReward]
PRIORITY_DATA_DARK_EVENT_EXTENSION_HOURS=436 ;672 ;336
WATCH_LIST_CONTACT_COST_MOD=0.5 ;0.1 ;0.67
INSIGHT_TECH_COMPLETION_MOD=0.5 ;0.1 ;0.67
SATELLITE_DATA_SCAN_RATE_MOD=0.3 ;0.1 ;0.5
SATELLITE_DATA_SCAN_RATE_DURATION_HOURS=872 ;1272 ;672
ENEMY_PROTOCOL_HACKING_BONUS=20 ;50 ;10
VIPER_ROUNDS_APPLICATION_CHANCE=12

[LW_Overhaul.X2HackReward_LWOverhaul]

SapperApplicationChance=35 ;65 ;25
WilltoSurviveApplicationChance=25 ;55 ;15
CenterMassApplicationChance=26 ;56 ;16
LethalApplicationChance=18 ;48 ;8
InfighterApplicationChance=60 ;90 ;50
FormidableApplicationChance=25 ;55 ;15
ShredderApplicationChance=26 ;56 ;16
DeadShotApplicationChance=43 ;83 ;33
LightningReflexesApplicationChance=30 ;80 ;20
CloseCombatSpecialistApplicationChance=100
GrazingFireApplicationChance=35 ;75 ;25
CutthroatApplicationChance=77 ;100 ;67
CombatAwarenessApplicationChance=60 ;90 ;50
IronSkinApplicationChance=100
TacticalSenseApplicationChance=60 ;90 ;50
AggressionApplicationChance=30 ;60 ;20
ResilienceApplicationChance=100
ShadowstepApplicationChance=100
DamageControlApplicationChance=30 ;60 ;20
HardTargetApplicationChance=35 ;65 ;25
GreaterFacelessApplicationChance=85 ;100 ;75

[NetworkTowerImpair_LW_T0 X2HackRewardTemplate]
MinHackSuccess=0
MinTurnsUntilExpiration=3 ;4 ;2
MaxTurnsUntilExpiration=3 ;4 ;2

;; HACK / INSTRUSION REWARDS

;; SKULLJACK

[SkulljackLootIntel_T1 X2HackRewardTemplate]
MinHackSuccess=10 ;0 ;23
HackSuccessVariance=10

[SkulljackLootIntel_T2 X2HackRewardTemplate]
MinHackSuccess=25 ;0 ;55
HackSuccessVariance=10

;; SKULLMINE
[SKULLFeedback X2HackRewardTemplate]
MinHackSuccess=0

[ALittleIntel X2HackRewardTemplate]
MinHackSuccess=10 ;0 ;23
HackSuccessVariance=10

[ALotOfIntel X2HackRewardTemplate]
MinHackSuccess=25 ;0 ;55
HackSuccessVariance=10

[LWUtilities.Helpers_LW]
; Allow appearance of the "Restart Mission" button on all missions in non-Ironman/Ironman Games. Setting second button to true will allow LW-style Bronzeman mode.
EnableRestartMissionButtonInNonIronman=true
EnableRestartMissionButtonInIronman=false ;true ;false
