;;---------------------------------------------------------------------------------------------
;; [LWOTC] A Better Rookie (LITE)
;;---------------------------------------------------------------------------------------------
;;---------------------------------------------------------------------------------------------
;;-- DIY Modding:
;;-- On each line that has been changed is a value after the ";" to the far right.  
;;-- This is the original value the game defined after a XCOM2 devs spent a zillion hours of 
;;-- game testing and balancing. If you do not like the value I gave you can choose a new one 
;;-- knowing both what XCOM2/WOTC intended and what I gave it.
;;
;;-- BLADEMASTER_DMG=10	;# non-LITE value ;# game original value
;;-- BLADEMASTER_DMG=2 ;3 ;1
;;-- 
;;----------------------------------------------------------------------------------------------
[LW_Overhaul.LWTemplateMods]
FIRST_ROOKIE_DIES[0]=FALSE
FIRST_ROOKIE_DIES[1]=FALSE ;FALSE ;TRUE
FIRST_ROOKIE_DIES[2]=TRUE ;FALSE ;TRUE
FIRST_ROOKIE_DIES[3]=TRUE
; Item config


[LW_Overhaul.X2LWAbilitiesModTemplate]
; negative dodge creates chances for promotion of hit types, similar to crit
ALLOW_NEGATIVE_DODGE=true
; allowing dodge to convert grazes to misses will reduce the overall hit chance, displaying a modifier 
DODGE_CONVERTS_GRAZE_TO_MISS=true

; This will cause all abilities with the guaranteed hit template to ignore the graze band value (this includes HoB, Clutch Shot, and all the heavy weapons)
; This does not override dodge mechanics
GUARANTEED_HIT_ABILITIES_IGNORE_GRAZE_BAND=true

; Per-difficulty enabling of the Headshot ability
HEADSHOT_ENABLED[0]=true
HEADSHOT_ENABLED[1]=true
HEADSHOT_ENABLED[2]=true ;true ;false
HEADSHOT_ENABLED[3]=false ;true ;false

; Number of charges for each level of Teamwork
TEAMWORK_LVL1_CHARGES=2 ;3 ;1
TEAMWORK_LVL2_CHARGES=2 ;3 ;1
TEAMWORK_LVL3_CHARGES=3 ;4 ;2

; Reduce the ability of Reapers to crit and stay stealthed
SHADOW_CRIT_MODIFIER=-10 ;0 ;-30

[LW_Overhaul.X2LWCovertActionsModTemplate]
; Required soldier ranks to go on the "Find Faction" covert actions
FIND_SECOND_FACTION_REQ_RANK=4  ; SGT
FIND_THIRD_FACTION_REQ_RANK=5   ; SSGT

; Required soldier ranks to go on the "Find Faction" covert actions
FIRST_CHOSEN_CA_REQ_RANK=4  ; SGT
SECOND_CHOSEN_CA_REQ_RANK=6 ; TSGT
THIRD_CHOSEN_CA_REQ_RANK=8  ; MSGT

[LW_Overhaul.X2EventListener_Soldiers]
; Vanilla is based on will score minus a configurable penalty. This instead bases it on the overkill damage -- how much damage the soldier took beyond zero. 
; These settings mean a 90% to bleed out rather than die at exactly 0 hp, 70% at -1 hp, 50% at -2 hp, etc.
BLEEDOUT_CHANCE_BASE=100 ;120 ;90
DEATH_CHANCE_PER_OVERKILL_DAMAGE=10 ;5 ;20

; This is how many additional squaddie abilities a newly trained psi receives. They are picked randomly from the first two levels. 3 means you get all 1st and 2nd level abilities
PSI_SQUADDIE_BONUS_ABILITIES=3

; This means use RANK * AWC respec times setting, if false, just use the setting with no multiplier by rank
TIERED_RESPEC_TIMES=true ;false ;true