;;---------------------------------------------------------------------------------------------
;; [LWOTC] A Better Rookie (LITE)
;;---------------------------------------------------------------------------------------------
;;---------------------------------------------------------------------------------------------
;;-- DIY Modding:
;;-- On each line that has been changed is a value after the ";" to the far right.  
;;-- This is the original value the game defined after a XCOM2 devs spent a zillion hours of 
;;-- game testing and balancing. If you do not like the value I gave you can choose a new one 
;;-- knowing both what XCOM2/WOTC intended and what I gave it.
;;
;;-- BLADEMASTER_DMG=10	;# non-LITE value ;# game original value
;;-- BLADEMASTER_DMG=2 ;3 ;1
;;-- 
;;----------------------------------------------------------------------------------------------

[LW_OfficerPack_Integrated.UIArmory_LWOfficerPromotion]
; debug settings
ALWAYSSHOW=false ;true ;false			;display all future abilities instead of displaying "locked" 
ALLOWTRAININGINARMORY=false ;true ;false	;allows training of abilities when UI accessed from Armory, not just fro0m OTS
INSTANTTRAINING=false		;trains abilities instantly instead of creating officer training project

[LW_OfficerPack_Integrated.X2Ability_OfficerAbilitySet]
;range measured in tiles
BaseCommandRange=8.1
CommandRangePerRank=1.0

;multiplier on officer command range, broken down by difficulty
COMMANDRANGE_DIFFICULTY_MULTIPLER[0]=1.3f
COMMANDRANGE_DIFFICULTY_MULTIPLER[1]=1.0f
COMMANDRANGE_DIFFICULTY_MULTIPLER[2]=1.0f
COMMANDRANGE_DIFFICULTY_MULTIPLER[3]=1.0f

; -------------- BEGIN CONFIG FOR SPECIFIC OFFICER ABILITIES ---------------------- ;

GETSOME_ACTIONPOINTCOST=1 ;0 ;1
GETSOME_CRIT_BONUS=30 ;50 ;20
GETSOME_CHARGES=2 ;3 ;2
GETSOME_DURATION=1 ;2 ;1

FALLBACK_COOLDOWN=3 ;1 ;4

OSCARMIKE_ACTIONPOINTCOST=1 ;0 ;1
OSCARMIKE_CHARGES=1 ;3 ;1
OSCARMIKE_DURATION=1 ;2 ;1
OSCARMIKE_MOBILITY_BONUS=6 ;8 ;5

COLLECTOR_BONUS_INTEL_LOW=2 ;3 ;1
COLLECTOR_BONUS_INTEL_RANDBONUS=0
COLLECTOR_BONUS_CHANCE=43 ;63 ;33
COLLECTOR_MAX_INTEL_PER_MISSION=20 ;50 ;10

INCOMING_COOLDOWN=3 ;2 ;5
INCOMING_EXPLOSIVES_DR=4
AIR_CONTROLLER_EVAC_TURN_REDUCTION=2
JAMMER_CHARGES=2 ;3 ;1
JAMMER_ACTION_POINTS=1

; infiltration bonuses set in infiltration ini
LEADERSHIP_WILL_PER_MISSION=5 ;10 ;1
LEADERSHIP_WILL_CAP=75 ;100 ;40
LEADERSHIP_DODGE_PER_MISSION=1 ;5 ;0.5
LEADERSHIP_DODGE_CAP=20 ;50 ;10
LEADERSHIP_AIM_PER_MISSION=1 ;2 ;0
LEADERSHIP_AIM_CAP=20 ;50 ;0
LEADERSHIP_DEFENSE_PER_MISSION=1 ;2 ;0
LEADERSHIP_DEFENSE_CAP=20 ;30 ;0

TRIAL_BY_FIRE_RANK_CAP=4

[LW_OfficerPack_Integrated.X2Ability_OfficerAbilitySet_PassiveAuras]
FIREDISCIPLINE_REACTIONFIRE_BONUS=10

[LW_OfficerPack_Integrated.X2Effect_Defilade]
DEFILADE_DEFENSE_BONUS=5

[LW_OfficerPack_Integrated.X2Effect_CombinedArms]
COMBINEDARMS_DAMAGE_BONUS=1

[LW_OfficerPack_Integrated.X2Effect_FocusFire]
FOCUSFIRE_ACTIONPOINTCOST=1
FOCUSFIRE_COOLDOWN=3 ;2 ;3
FOCUSFIRE_DURATION=1 ;2 ;1
ARMORPIERCINGEFFECT=1 ;2 ;1
AIMBONUSPERATTACK=6 ;8 ;5
VALIDWEAPONCATEGORIES[0]="rifle"
VALIDWEAPONCATEGORIES[1]="shotgun"
VALIDWEAPONCATEGORIES[2]="cannon"
VALIDWEAPONCATEGORIES[3]="sniper_rifle"
VALIDWEAPONCATEGORIES[4]="pistol"
VALIDWEAPONCATEGORIES[5]="sword"
VALIDWEAPONCATEGORIES[6]="smg"
VALIDWEAPONCATEGORIES[7]="vektor_rifle"
VALIDWEAPONCATEGORIES[8]="bullpup"
VALIDWEAPONCATEGORIES[9]="wristblade"
VALIDWEAPONCATEGORIES[10]="gauntlet"  ; Templar Gauntlet
VALIDWEAPONCATEGORIES[11]="sidearm"

[LW_OfficerPack_Integrated.X2Effect_Scavenger]
;bonus mission supplies from Scavenger ability
SCAVENGER_BONUS_MULTIPLIER = 0.5f ;0.75f ;0.3f
;chance to retain each item on second Scavenger auto-loot roll
;SCAVENGER_AUTOLOOT_CHANCE = 0.3f
;values from force level 0 to force level 20
SCAVENGER_AUTOLOOT_CHANCE_MIN=0.3f
SCAVENGER_AUTOLOOT_CHANCE_MAX=0.4f
SCAVENGER_AUTOLOOT_NUMBER_MIN=1.0f
SCAVENGER_AUTOLOOT_NUMBER_MAX=3.5f
SCAVENGER_ELERIUM_TO_ALLOY_RATIO=0.6f
;resource types that can be obtained on Scavenger auto-loot roll
;VALID_SCAVENGER_AUTOLOOT_TYPES[0]=AlienAlloy
;VALID_SCAVENGER_AUTOLOOT_TYPES[1]=EleriumDust
SCAVENGER_MAX_PER_MISSION=15 ;20 ;10